### ISSUE TITLE
Doesn't work for multiple receivers

### ISSUE THREAD

**Issue by achin42** [cheminfo/pm2-bridge#2]
Hello. I need to do ipc from a sender to multiple receiver processes. pm2-bridge works fine when there is one sender and one receiver but outputs following error for any more receivers

```
pv1m-24 { data: 'ping', from: 'pv1' }
pv1m-24 { data: 'ping', from: 'pv1' }
pv1-25  { data: 'some data' }
pv1-26  Error: timeout exceeded
pv1-26     at Timeout._onTimeout (/Users/Infernus/ProjectsNode/probe/node_modules/pm2-bridge/src/index.js:76:24)
pv1-26     at tryOnTimeout (timers.js:228:11)
pv1-26     at Timer.listOnTimeout (timers.js:202:5)
```

Here's the code I'm using. Same script is being used for master and other processes. I'm telling them apart by using command line args in ecosystem.json.

```
if (!isMaster) {
    // This block will run once by each receiver process.
    pm2Bridge.send({
        to: 'pv1m', // send something to the process with the pm2 name 'receiver'
        data: 'ping' // Send some data along
    }).then(function(message) {
        // Receive the receiver's reply
        console.log(message.data); // pong
    }, function(err) {
        // Something went wrong :(
        // for example the receiver was not found
        console.error(err);
    });
} else {
    // This block will run once for each receiver process and would reply to their message.
    pm2Bridge.onMessage(function(message, context) {
        console.log(message); // {from: 'sender', data: 'ping'}
        context.reply({data: "some data"}); // Reply to the sender
    });
}
```

Thanks

**Comment by stropitek** [comment]
Hello
From my understanding of the code snippet you have several senders (the slaves) and 1 receiver (the master). But your description says there are several receivers, so I'm a little confused.

Multiple receivers to one message is not possible with this library (the `to` argument when sending a message cannot be an array)

I see that I haven't implemented tests for processes concurrently sending messages to one receiver. I expect it to work though since messages all have unique ids so that they know who they should reply to when they receive a response.
